steps:
  - name: gcr.io/k8s-skaffold/pack
    entrypoint: pack
    args:
      - build
      - ${_IMAGE}
      - --builder
      - gcr.io/buildpacks/builder:v1
      - --path
      - .
      - --env
      - BP_JVM_VERSION=17

images:
  - ${_IMAGE}

substitutions:
  _IMAGE: asia-northeast3-docker.pkg.dev/$PROJECT_ID/shathing/shathing-backend
