spring:
  profiles.default: local

  mvc.throw-exception-if-no-handler-found: true

  web.resources.add-mappings: false

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa.hibernate:
    show-sql: true
    database: postgresql

  mail:
    host: smtp.gmail.com
    port: 587
    properties.mail.smtp:
      auth: true
      starttls.enable: true

  security.oauth2.client.registration.google:
    scope:
      - openid
      - profile
      - email

app:
  name: Shathing
  region:
    korea:
      csv-path: data/국토교통부_전국 법정동_20250807.csv
    us:
      states-path: data/2025_Gaz_state_national.txt
      counties-path: data/2025_Gaz_counties_national.txt

server.forward-headers-strategy: framework