spring:
  application:
    name: backend

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - openid
              - profile
              - email
            redirect-uri: ${APP_API_URL}/login/oauth2/code/google

  profiles:
    default: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
      show-sql: true
      database: postgresql

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true

app:
  category:
    initialize-on-startup: ${CATEGORY:false}
  region:
    initialize-on-startup: ${REGION:false}
    korea:
      csv-path: data/국토교통부_전국 법정동_20250807.csv
    us:
      states-path: data/2025_Gaz_state_national.txt
      counties-path: data/2025_Gaz_counties_national.txt

server:
  forward-headers-strategy: framework

R2_ENDPOINT: ${R2_ENDPOINT:}
R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID:}
R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY:}
R2_BUCKET_NAME: ${R2_BUCKET_NAME:}
R2_PUBLIC_BASE_URL: ${R2_PUBLIC_BASE_URL:}
R2_PRESIGNED_URL_EXPIRATION_MINUTES: ${R2_PRESIGNED_URL_EXPIRATION_MINUTES:10}
